version: '2'
services:
  api:
    image: courier:latest
    ports:
      - "8000:8000"
    environment:
      - COURIER_PORT=:8000
      - SMTP_PORT=587
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USER=$YOUR_EMAIL
      - SMTP_PASSWORD=$YOUR_PASSWORD