// Code generated by protoc-gen-go. DO NOT EDIT.
// source: courier.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	courier.proto

It has these top-level messages:
	SendBody
	Response
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_Success Status = 0
	Status_Fail    Status = 1
)

var Status_name = map[int32]string{
	0: "Success",
	1: "Fail",
}
var Status_value = map[string]int32{
	"Success": 0,
	"Fail":    1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SendBody struct {
	Sender      string   `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Recipients  []string `protobuf:"bytes,2,rep,name=recipients" json:"recipients,omitempty"`
	Cc          []string `protobuf:"bytes,3,rep,name=cc" json:"cc,omitempty"`
	Bcc         []string `protobuf:"bytes,4,rep,name=bcc" json:"bcc,omitempty"`
	Attachments []string `protobuf:"bytes,5,rep,name=attachments" json:"attachments,omitempty"`
	Subject     string   `protobuf:"bytes,6,opt,name=subject" json:"subject,omitempty"`
	BodyText    string   `protobuf:"bytes,7,opt,name=bodyText" json:"bodyText,omitempty"`
	BodyType    string   `protobuf:"bytes,8,opt,name=bodyType" json:"bodyType,omitempty"`
}

func (m *SendBody) Reset()                    { *m = SendBody{} }
func (m *SendBody) String() string            { return proto.CompactTextString(m) }
func (*SendBody) ProtoMessage()               {}
func (*SendBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SendBody) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SendBody) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *SendBody) GetCc() []string {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *SendBody) GetBcc() []string {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *SendBody) GetAttachments() []string {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *SendBody) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendBody) GetBodyText() string {
	if m != nil {
		return m.BodyText
	}
	return ""
}

func (m *SendBody) GetBodyType() string {
	if m != nil {
		return m.BodyType
	}
	return ""
}

type Response struct {
	Status  Status `protobuf:"varint,1,opt,name=status,enum=courier.Status" json:"status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_Success
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendBody)(nil), "courier.SendBody")
	proto.RegisterType((*Response)(nil), "courier.Response")
	proto.RegisterEnum("courier.Status", Status_name, Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mail service

type MailClient interface {
	Send(ctx context.Context, in *SendBody, opts ...grpc.CallOption) (*Response, error)
}

type mailClient struct {
	cc *grpc.ClientConn
}

func NewMailClient(cc *grpc.ClientConn) MailClient {
	return &mailClient{cc}
}

func (c *mailClient) Send(ctx context.Context, in *SendBody, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/courier.Mail/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mail service

type MailServer interface {
	Send(context.Context, *SendBody) (*Response, error)
}

func RegisterMailServer(s *grpc.Server, srv MailServer) {
	s.RegisterService(&_Mail_serviceDesc, srv)
}

func _Mail_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/courier.Mail/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServer).Send(ctx, req.(*SendBody))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mail_serviceDesc = grpc.ServiceDesc{
	ServiceName: "courier.Mail",
	HandlerType: (*MailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Mail_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "courier.proto",
}

func init() { proto.RegisterFile("courier.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x1a, 0x92, 0xf4, 0x2a, 0x4a, 0xb9, 0x01, 0x59, 0x1d, 0x20, 0xea, 0x42, 0x85,
	0x50, 0x87, 0xc2, 0x2f, 0xe8, 0xc0, 0xd6, 0x25, 0x61, 0x62, 0x73, 0x2e, 0x27, 0x08, 0x6a, 0x63,
	0x2b, 0x76, 0x24, 0xf2, 0x4f, 0xf9, 0x39, 0x28, 0x6e, 0xd2, 0x66, 0xf3, 0xfb, 0x9e, 0xe5, 0x7b,
	0x7e, 0x07, 0x37, 0xa4, 0x9a, 0xba, 0xe4, 0x7a, 0xa3, 0x6b, 0x65, 0x15, 0x46, 0xbd, 0x5c, 0xfd,
	0x79, 0x10, 0x67, 0x5c, 0x15, 0x3b, 0x55, 0xb4, 0x78, 0x0f, 0xa1, 0xe1, 0xaa, 0xe0, 0x5a, 0x78,
	0x89, 0xb7, 0x9e, 0xa6, 0xbd, 0xc2, 0x07, 0x80, 0x9a, 0xa9, 0xd4, 0x25, 0x57, 0xd6, 0x08, 0x3f,
	0x99, 0xac, 0xa7, 0xe9, 0x88, 0xe0, 0x1c, 0x7c, 0x22, 0x31, 0x71, 0xdc, 0x27, 0xc2, 0x05, 0x4c,
	0x72, 0x22, 0x11, 0x38, 0xd0, 0x1d, 0x31, 0x81, 0x99, 0xb4, 0x56, 0xd2, 0xf7, 0xd1, 0x3d, 0x71,
	0xed, 0x9c, 0x31, 0x42, 0x01, 0x91, 0x69, 0xf2, 0x1f, 0x26, 0x2b, 0x42, 0x37, 0x7c, 0x90, 0xb8,
	0x84, 0x38, 0x57, 0x45, 0xfb, 0xc1, 0xbf, 0x56, 0x44, 0xce, 0x3a, 0xeb, 0xb3, 0xd7, 0x6a, 0x16,
	0xf1, 0xc8, 0x6b, 0x35, 0xaf, 0xf6, 0x10, 0xa7, 0x6c, 0xb4, 0xaa, 0x0c, 0xe3, 0x13, 0x84, 0xc6,
	0x4a, 0xdb, 0x18, 0xf7, 0xb3, 0xf9, 0xf6, 0x76, 0x33, 0xf4, 0x91, 0x39, 0x9c, 0xf6, 0x76, 0x17,
	0xe3, 0xc8, 0xc6, 0xc8, 0x2f, 0x16, 0xfe, 0x29, 0x46, 0x2f, 0x9f, 0x1f, 0x21, 0x3c, 0xdd, 0xc5,
	0x19, 0x44, 0x59, 0x43, 0xc4, 0xc6, 0x2c, 0xae, 0x30, 0x86, 0xe0, 0x5d, 0x96, 0x87, 0x85, 0xb7,
	0x7d, 0x83, 0x60, 0x2f, 0xcb, 0x03, 0xbe, 0x40, 0xd0, 0x35, 0x8a, 0x77, 0x97, 0x19, 0x7d, 0xc1,
	0xcb, 0x0b, 0x1a, 0x92, 0xed, 0x82, 0x4f, 0x5f, 0xe7, 0x79, 0xe8, 0xd6, 0xf2, 0xfa, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0x19, 0xa0, 0xbf, 0x9d, 0xa7, 0x01, 0x00, 0x00,
}
